const express=require('express')
const router=express.Router()
const {deleteaddress,updateaddress,fetechspecificaddress,fetchaddress,addaddress,updatecartminus,updatecartplus,fetchcart,addcart,refreshToken,categoryname,fetchrecom,getProducts,signup,verifyotp,resendotp,googleLogin, login, fetchproductdetails}=require('./Controller/userController')
const passport = require('passport')
const verifyAccessToken =require( './middleware/verifyaccessToken')

router.post('/signup',signup)
router.post('/refresh',refreshToken)
router.post('/login',login)
router.post('/verifyotp',verifyotp)
router.post('/resendotp',resendotp)
router.post('/auth/google',googleLogin)
router.get('/getproducts',verifyAccessToken,getProducts)
router.get('/products/display/:id',verifyAccessToken,fetchproductdetails)
router.get('/products/recommendations/:category',verifyAccessToken,fetchrecom)
router.get('/fetchcategory',categoryname)
router.post('/addcart',verifyAccessToken,addcart)
router.get('/fetchcart/:userId',verifyAccessToken,fetchcart)
router.put('/updatecartminus/:userId',verifyAccessToken,updatecartminus)
router.put('/updatecartplus/:userId',verifyAccessToken,updatecartplus)
router.post('/addaddress',verifyAccessToken,addaddress)
router.get('/fetchaddress/:userId', verifyAccessToken,fetchaddress)
router.get('/fetechspecificaddress/:id',verifyAccessToken,fetechspecificaddress)
router.put('/updateaddress/:id',verifyAccessToken,updateaddress)
router.delete('/deleteaddress/:id',verifyAccessToken,deleteaddress)
module.exports=router